import requests
from bs4 import BeautifulSoup

# url = "https://www.mims.com/vietnam/SsoMembership/LogOn?dnoa.userSuppliedIdentifier=https%3A%2F%2Fsso.mims.com%2F"
url = "https://sso.mims.com/Authentication/Authenticate"
form_data={
  "openid.claimed_id": "https://sso.mims.com/user/3085062",
  "openid.identity": "https://sso.mims.com/user/3085062",
  "openid.sig": "FggYJRlVHC/U5jdh31LjULquu6WpAt44iR3YcrHgiyY=",
  "openid.signed": "claimed_id,identity,assoc_handle,op_endpoint,return_to,response_nonce,ns.alias3,alias3.mode,alias3.type.alias1,alias3.value.alias1,alias3.type.alias2,alias3.value.alias2,alias3.type.alias3,alias3.value.alias3,alias3.type.alias4,alias3.value.alias4,alias3.type.alias5,alias3.value.alias5,alias3.type.alias6,alias3.value.alias6,alias3.type.alias7,alias3.value.alias7,alias3.type.alias8,alias3.value.alias8,alias3.type.alias9,alias3.value.alias9,alias3.type.alias10,alias3.value.alias10,alias3.type.alias11,alias3.value.alias11,alias3.type.alias12,alias3.value.alias12,alias3.type.alias13,alias3.value.alias13,alias3.type.alias14,alias3.value.alias14,alias3.type.alias15,alias3.value.alias15,alias3.type.alias16,alias3.value.alias16,alias3.type.alias17,alias3.value.alias17,alias3.type.alias18,alias3.value.alias18,alias3.type.alias19,alias3.value.alias19,alias3.type.alias20,alias3.value.alias20,alias3.type.alias21,alias3.value.alias21,alias3.type.alias22,alias3.value.alias22,alias3.type.alias23,alias3.value.alias23,alias3.type.alias24,alias3.value.alias24,alias3.type.alias25,alias3.value.alias25,alias3.type.alias26,alias3.value.alias26,alias3.type.alias27,alias3.value.alias27,alias3.type.alias28,alias3.value.alias28,alias3.type.alias29,alias3.value.alias29,alias3.type.alias30,alias3.value.alias30,alias3.type.alias31,alias3.value.alias31,alias3.type.alias32,alias3.value.alias32,alias3.type.alias33,alias3.value.alias33",
  "openid.assoc_handle": "0xuQ!IAAAABtG_yxl_WXUyrm5wX9jbCSy2cZNmXv9pCQD-14RxncfQQAAAAEZ_G0ObTdNEoFNSvlzYmkAlhjnXUeqgjBiSeWCtWbtYisfR7FgLs2oEFmYoqSo_6aKVLkyHjI3BSWoDlIHZMSd",
  "openid.op_endpoint": "https://sso.mims.com/Authentication/Authenticate",
  "openid.return_to": "http://www.mims.com/vietnam/SsoMembership/LogOn?dnoa.userSuppliedIdentifier=https%3A%2F%2Fsso.mims.com%2F",
  "openid.response_nonce": "2019-11-01T03:00:44ZcG16dZ3s",
  "openid.mode": "id_res",
  "openid.ns": "http://specs.openid.net/auth/2.0",
  "openid.ns.alias3": "http://openid.net/srv/ax/1.0",
  "openid.alias3.mode": "fetch_response",
  "openid.alias3.type.alias1": "title",
  "openid.alias3.value.alias1": "Mr.",
  "openid.alias3.type.alias2": "first",
  "openid.alias3.value.alias2": "Tài",
  "openid.alias3.type.alias3": "last",
  "openid.alias3.value.alias3": "Nguyễn",
  "openid.alias3.type.alias4": "middle",
  "openid.alias3.value.alias4": "",
  "openid.alias3.type.alias5": "email",
  "openid.alias3.value.alias5": "taibeoka1996@gmail.com",
  "openid.alias3.type.alias6": "gender",
  "openid.alias3.value.alias6": "",
  "openid.alias3.type.alias7": "address",
  "openid.alias3.value.alias7": "",
  "openid.alias3.type.alias8": "postal",
  "openid.alias3.value.alias8": "",
  "openid.alias3.type.alias9": "state",
  "openid.alias3.value.alias9": "",
  "openid.alias3.type.alias10": "mobile",
  "openid.alias3.value.alias10": "",
  "openid.alias3.type.alias11": "office",
  "openid.alias3.value.alias11": "",
  "openid.alias3.type.alias12": "home",
  "openid.alias3.value.alias12": "",
  "openid.alias3.type.alias13": "fax",
  "openid.alias3.value.alias13": "",
  "openid.alias3.type.alias14": "country",
  "openid.alias3.value.alias14": "VN",
  "openid.alias3.type.alias15": "profession",
  "openid.alias3.value.alias15": "DENTIST",
  "openid.alias3.type.alias16": "specialty",
  "openid.alias3.value.alias16": "DENTAL PUBLIC HEALTH",
  "openid.alias3.type.alias17": "rank",
  "openid.alias3.value.alias17": "",
  "openid.alias3.type.alias18": "licence",
  "openid.alias3.value.alias18": "",
  "openid.alias3.type.alias19": "identitycard",
  "openid.alias3.value.alias19": "",
  "openid.alias3.type.alias20": "university",
  "openid.alias3.value.alias20": "",
  "openid.alias3.type.alias21": "createdip",
  "openid.alias3.value.alias21": "113.161.94.15",
  "openid.alias3.type.alias22": "createdcountry",
  "openid.alias3.value.alias22": "VN",
  "openid.alias3.type.alias23": "practicename",
  "openid.alias3.value.alias23": "",
  "openid.alias3.type.alias24": "department",
  "openid.alias3.value.alias24": "",
  "openid.alias3.type.alias25": "practiceaddress",
  "openid.alias3.value.alias25": "",
  "openid.alias3.type.alias26": "gradyear",
  "openid.alias3.value.alias26": "0",
  "openid.alias3.type.alias27": "pic",
  "openid.alias3.value.alias27": "",
  "openid.alias3.type.alias28": "IsPersistentCookie",
  "openid.alias3.value.alias28": "False",
  "openid.alias3.type.alias29": "authtoken",
  "openid.alias3.value.alias29": "643941762d2a4d7890a057c20bd7e41a",
  "openid.alias3.type.alias30": "profilepicture",
  "openid.alias3.value.alias30": "",
  "openid.alias3.type.alias31": "wechatid",
  "openid.alias3.value.alias31": "",
  "openid.alias3.type.alias32": "verificationstatus",
  "openid.alias3.value.alias32": "",
  "openid.alias3.type.alias33": "kol",
  "openid.alias3.value.alias33": "False"
}

req = requests.post(url, data=form_data, stream=True, timeout=20)
soup = BeautifulSoup(req.text, 'html.parser')
print(soup)
